UI dashboard (#29)
* [Styles] Update Tailwind configuration with new font sizes and colors; add custom text stroke utility

* [Styles] Remove unused font-face declarations and enhance font smoothing in globals.css

* [Styles] Adjust max-width and margin for personContainer in Organisation, Person, and Project page components

* [Styles] Update

* [Styles] Rearrange AffiliationsComponent placement in OrganisationPageComponent

* [Styles] Dateformat now shows just Y and update icon, tagline and typography styles

* [Styles] Small changes

* [Update] build update

* [Fix] Add optional chaining to prevent runtime errors in OrganisationPageComponent and related components

* Yarn build

* Refactor TagListComponent to use optional chaining for tagList

* [Refactor] TagListComponent and TagThumbnail components

* [Refactor CSS] styles for global variables and button component

* Refactor TagListComponent to handle null tagList

* [Refactor] null handling in ProjectPageComponent and AffiliationsComponent

* [Refactor CSS] Update global variables and button component styles

* Merge branch 'main' of https://github.com/szergen/futures4europe into catalin

* Merge branch 'info-pages-person' of https://github.com/szergen/futures4europe into catalin

* Update font and tag styles

* [Null fix] Fix null check in array length comparison

* [ CSS and small refactors] Updates

* Refactor affiliations component and update tag list styles

* Merge branch 'info-pages-project' of https://github.com/szergen/futures4europe into catalin

* [Refactor and style] affiliations component and update tag list styles

* [Refactor header]  component update and new elements

* [Style & Login] tailwind.config.js and globals.css files

* Refactor Header component: Move SVG icons to global import

* [Refactor] package.json and package-lock.json

* [UI] Search, Auth, Header

* [Dashboard] profile, security and password pages

* [Refactor, UI, Dashboard] tailwind.config.js and fix border-radius in pageDashboard.module.css

* Refactor flex alignment in DashboardProjects component

* Merge branch 'main' of https://github.com/szergen/futures4europe into ui-dashboard

* [ui-changes] Fixed build

* [Refactor UI] flex alignment in DashboardProjects component

* Refactor TagPicker component labels

* [account-fix] Fixed when accountID is missing

* [Refactor, Dashboard, Styles] Update color variables and styles, changes to dasboard, Added Org page dashboard, Changes to Lists.

* [Refactor] dashboard and sub-navigation components

* [Refactor] validation function for name in HeaderComponent

* [Refactor] RTEComponent to handle pasted text in the editor

* [error] "TypeError: media.startsWith is not a function"  new check ensures that the media variable is actually a string before trying to call startsWith() on it. This prevents the TypeError.

* [Refactor] ContentComponent to handle content images with captions

* [New icon] SpriteSvg to add EditImageIcon

* [Refactor, Style] RTEComponent and ContentImageFileUploader

* [Refactor, Style, Code] Edit tag picker, links, list title, editMode Posts

* Yarn install

* [Delete] Button Add affilaition

* [ui-dashboard] Fixed lintings

---------

Co-authored-by: Catalin Sirbu <catalinssirbu@gmail.com>